### ISSUE TITLE
Morning Session Suggestions

### ISSUE THREAD

**Issue by topeogunleye** [topeogunleye/awesome-books#2]

**Comment by Vagyasri** [comment]
> ## Morning Session Suggestions

Hello @topeogunleye,

The project was built with lots of hard work, which we appreciate a lot. Also, the presentation was awesome. However, if you can add validation to the Book Name It can improve your project (It's not mandatory though).

**Comment by vic778** [comment]
hello @topeogunleye,
 well done your code looks very well

**Comment by edwardoluyara** [comment]
Actually there's nothing to be said rather than clean code and and great job

**Comment by topeogunleye** [comment]
Hey @Vagyasri, @oluyaratosin123 and @vic778, thank you for taking the time to check out my project. 🙏🏻
I'll definitely consider your feedback.
