### ISSUE TITLE
Morning Session Suggestions Nov 25

### ISSUE THREAD

**Issue by topeogunleye** [topeogunleye/awesome-books#5]
## Morning Session Suggestions

**Comment by Vagyasri** [comment]
Hello @topeogunleye,

The project seems nice. And, your great presentation made us understand it even better. There is some small scope of improvement as follows:

- You can use different font sizes for the `Title` and the `Author`
- You can use the same background colors for the header and footer.

Other than that everything seems great. All the best. Happy coding.

**Comment by topeogunleye** [comment]
Hey @Vagyasri and @oluyaratosin123, thank you for taking the time to check out my project. 🙏🏻
I'll definitely consider your feedback.

**Comment by vic778** [comment]
hey, @topeogunleye good job, but in your js file follow the microverse requirement, please.

**Comment by edwardoluyara** [comment]
Hey @topeogunleye this project looks great I don't think there's anything else to change "Great Job!"
